// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfV4i_pkevHzMDBpjbLbVlIY-_Ro7428',
    appId: '1:373568199465:web:5579f18e4ab4dbd9a2b538',
    messagingSenderId: '373568199465',
    projectId: 'detective-academy-1bd88',
    authDomain: 'detective-academy-1bd88.firebaseapp.com',
    storageBucket: 'detective-academy-1bd88.firebasestorage.app',
    measurementId: 'G-0DJEBX8PGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR-3ZlyPEspJ3bo3oSTXR8FMordJvF2Vk',
    appId: '1:373568199465:android:17dd628b5495ed05a2b538',
    messagingSenderId: '373568199465',
    projectId: 'detective-academy-1bd88',
    storageBucket: 'detective-academy-1bd88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcM4DkB-rb_FB0WqCJZ2B4eAPBYveTW2E',
    appId: '1:373568199465:ios:efb3baa43fd18efea2b538',
    messagingSenderId: '373568199465',
    projectId: 'detective-academy-1bd88',
    storageBucket: 'detective-academy-1bd88.firebasestorage.app',
    iosBundleId: 'com.excelerate.mad.detectiveAcademy',
  );
}
